/// Flutter icons Socicon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Socicon
///      fonts:
///       - asset: fonts/Socicon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Socicon {
  Socicon._();

  static const _kFontFam = 'Socicon';
  static const _kFontPkg = null;

  static const IconData facebook = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feedburner = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filmweb = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData firefox = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flattr = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flickr = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData formulr = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forrst = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData foursquare = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData friendfeed = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData goodreads = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData googlescholar = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData googlegroups = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData googlephotos = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData googleplus = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grooveshark = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hackerrank = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hearthstone = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
